In [64]:
instagram_id = 'your instagram user id'
hashtag = 'hashtag you wish to search for'
access_token = "your access token"

In [19]:
import requests
import json
graph_url = 'https://graph.facebook.com/v15.0/'
def get_hashtag_id(hashtag = hashtag,
                   instagram_account_id = instagram_id,
                   access_token = access_token):
    url = graph_url + 'ig_hashtag_search'
    param = dict()
    param['user_id'] = instagram_account_id
    param['q'] = hashtag
    param['access_token'] = access_token
    response = requests.get(url,param)
    response = response.json()
    hashtag_id = response['data'][0]['id']
    return hashtag_id

In [18]:
graph_url = 'https://graph.facebook.com/v15.0/'
def get_data_of_hashtag(hashtag_id = '',access_token=''):
    url = graph_url + hashtag_id
    param =dict()
    param['access_token'] = access_token
    param['fields'] = 'id,name'
    response = requests.get(url,param)
    response = response.json()
    return response

In [51]:
graph_url = 'https://graph.facebook.com/v15.0/'
def get_top_media(hashtag_id='',access_token='',instagram_account_id=''):
    url = graph_url + hashtag_id + '/top_media'
    param = dict()
    param['access_token'] = access_token
    param['user_id'] = instagram_account_id
    param['fields'] = 'caption,like_count,permalink,timestamp,comments_count,media_type'
    response = requests.get(url, param)
    response = response.json()
    print(response)
    return response

In [14]:
instagram_hashtag = get_hashtag_id()

In [17]:
instagram_hashtag_id = instagram_hashtag

In [22]:
a = get_data_of_hashtag(instagram_hashtag_id,
                        access_token=access_token)

In [52]:
b = get_top_media(instagram_hashtag_id,
                 access_token=access_token,
                 instagram_account_id=instagram_id)

{'data': [{'caption': '#youngthug’s lawyer now representing #problemchild ⚖️ rapspotsnews \nSwipe ➡️', 'like_count': 1820, 'permalink': 'https://www.instagram.com/p/DDxL4hlR6lR/', 'timestamp': '2024-12-19T17:35:30+0000', 'comments_count': 65, 'media_type': 'CAROUSEL_ALBUM', 'id': '18013719890662275'}, {'caption': '#YoungThug has filed a new motion to be given bond with the new judge who was recently assigned to the #YslTrial case.', 'permalink': 'https://www.instagram.com/p/C9yP2ThpgSt/', 'timestamp': '2024-07-24T00:21:01+0000', 'comments_count': 18, 'media_type': 'CAROUSEL_ALBUM', 'id': '18008405282548887'}, {'caption': "In YSL's RICO Case The Judge Reads Lyrics Off Thug's Slime Sh- In Court\n\nUsing His Lyrics In Court Is Crazy I Can't Lie..What Happened To Freedom of Speech? Thoughts ??", 'like_count': 621, 'permalink': 'https://www.instagram.com/p/CnHbvp3jENH/', 'timestamp': '2023-01-07T13:47:30+0000', 'comments_count': 80, 'media_type': 'VIDEO', 'id': '18266528860114452'}, {'caption': 'YSL Co-Founder Demonstrates Gang Signs in Court – A Shocking Tutorial Raises  Eyebrows. 🤔👀 #YSL #CourtroomControversy #YoungThug #YSLtrial', 'like_count': 36, 'permalink': 'https://www.instagram.com/p/C1pdT29PUHi/', 'timestamp': '2024-01-03T18:14:20+0000', 'comments_count': 3, 'media_type': 'CAROUSEL_ALBUM', 'id': '17908442528808076'}, {'caption': 'Looks like Mr. Thugger is already motivating the community & speaking to the upcoming lawyers at Emory Law School. Thoughts!? 🤔👇\n\n➕ Follow doaphouse for daily music updates, news & viral content!\n\n#youngthug #briansteel #thuggerthugger #emorylaw #ysltrial #freejeff #atlantarapper #atlrap #atlanatapolice #newmusicfriday #yslrecords #lawyer', 'permalink': 'https://www.instagram.com/p/DCFWvBzzQkx/', 'timestamp': '2024-11-07T20:32:21+0000', 'comments_count': 8, 'media_type': 'CAROUSEL_ALBUM', 'id': '18052871134937422'}, {'caption': 'We all know that #Wham is the nickname that #YoungThug uses for Lil Baby, so we think that whatever Lil Baby is doing on the outside YoungThug supports.... Hmm.. #Power983 #YSLTrial \n\n(Photo Credit: Arvin Temkar/Atlanta Journal-Constitution via AP, File)', 'permalink': 'https://www.instagram.com/p/C8urrFWPDOU/', 'timestamp': '2024-06-27T18:35:48+0000', 'comments_count': 1, 'media_type': 'IMAGE', 'id': '18016393640380619'}, {'caption': '🚨 BREAKING NEWS 🚨 Judge Ural Glanville presiding over the sweeping RICO indictment against Atlanta rapper Young Thug and his associates has been recused from the case. Judge Rachel Krause said in the motion that while the court has no doubt Glanville can and would continue presiding fairly over the case, but it is necessary to preserve “the public’s confidence in the judicial system.” The YSL Trial has been the subject of controversy since it started. 😳😬🏛️\n#YSLTrial #YoungThug #JudgeGlanville #BrianSteele #Atlanta #CultureClt™', 'permalink': 'https://www.instagram.com/p/C9dIZoiB8iW/', 'timestamp': '2024-07-15T19:31:54+0000', 'comments_count': 0, 'media_type': 'IMAGE', 'id': '18023226593256628'}, {'caption': 'Mannnn. What do yall think about this? 🤔\n#youngthug #gunna #ysltrial', 'like_count': 1879, 'permalink': 'https://www.instagram.com/p/C8uhezNCXBQ/', 'timestamp': '2024-06-27T17:06:45+0000', 'comments_count': 123, 'media_type': 'CAROUSEL_ALBUM', 'id': '18039000883787349'}, {'caption': 'This the new judge on #YoungThug’s Rico court trial 👀 How we feeling bout this? \n\n-\n-\n-\n\n#youngthug #thug #thugger #youngthugger #ysl #yslcase #ysltrial #judge #courtroom #youngthugs #slime #slatt #explore #explorepage #exploremore #explorepage #explorepage✨', 'permalink': 'https://www.instagram.com/p/C9i0Q6hJlK-/', 'timestamp': '2024-07-18T00:31:23+0000', 'comments_count': 4, 'media_type': 'IMAGE', 'id': '18038591872958710'}, {'caption': '#ysltrial isn’t over yet and continues Monday with #yslsb and #yakgotti expecting to take it to the jury ⚖️ rapspotsnews', 'like_count': 604, 'permalink': 'https://www.instagram.com/p/DB4dWq7RSG1/', 'timestamp': '2024-11-02T20:20:04+0000', 'comments_count': 12, 'media_type': 'IMAGE', 'id': '18317631610095385'}, {'caption': 'Ieri 27 novembre, è ufficialmente iniziato il processo contro YSL🤞🏻\n\nTrattandosi del primo giorno, non ci sono ancora state novità importanti…sono stati letti un paio di testi del rapper e gli sono state fatte le prime domande.\n\nSi stima che il processo duri dai 6 ai 9 mesi, di conseguenza, ne sentiremo parlare per un bel\npo’…\n\nSeguiranno aggiornamenti.\n.\n.\n.\n.\n#4theculture #youngthug #youngthugtrial #ysltrial #rap #trap #drill #hiphop #rapper #rapamericano', 'like_count': 1107, 'permalink': 'https://www.instagram.com/p/C0MAKZtNf8D/', 'timestamp': '2023-11-28T11:10:16+0000', 'comments_count': 7, 'media_type': 'IMAGE', 'id': '17989767533446039'}, {'caption': 'Abbiamo una data📆\n\nSi prevede che il 27 novembre, possa finalmente iniziare il tanto atteso processo contro Young Thug, e in generale YSL.\n\nDopo mesi di lavoro, qualche ora fa, è finalmente terminata la selezione della giuria, che sarà formata da 12 persone, più 6 eventuali sostituti.\n\nIl processo dovrebbe durare dai 6 ai 9 mesi, il che lo renderebbe, il più lungo nella storia della Georgia.\n\nNon ci resta che aspettare e sperare che vada tutto bene.\n\nSeguiranno aggiornamenti.\n.\n.\n.\n.\n#4theculture #youngthug #ysl #youngthugtrial #ysltrial #rap #trap #drill #hiphop #rapper #rapamericano', 'like_count': 922, 'permalink': 'https://www.instagram.com/p/CzJJVVDtFsA/', 'timestamp': '2023-11-02T12:01:17+0000', 'comments_count': 11, 'media_type': 'IMAGE', 'id': '18018357283884638'}, {'caption': 'Ci sono piccoli progressi per quanto riguarda il processo di Young Thug👀\n\n📲Sono stati ufficialmente selezionati 50 ‘probabili’ giurati, sui circa 1000 iniziali.\nQuesto significa che ora, passeremo allo step successivo.\n\nL’accusa e la difesa interrogheranno i restanti 50 giurati, decidendo chi scartare, per passare alla prossima fase.\n\nCiò andrà avanti fin quando rimarranno 12 giurati, più gli eventuali sostituti.\n\nPoiché si prevede un lungo processo, che durerà dai 6 ai 9 mesi, il giudice, molto probabilmente, richiederà un gran numero di sostituti, che entreranno in gioco solo nel caso in cui, qualcuno dei 12 prescelti dovesse abbandonare il processo, per qualsiasi tipo di emergenza.\n\nQuesto significa che questa fase, teoricamente, dovrebbe durare molto di meno rispetto alle precedenti e, una volta terminata, potrà finalmente iniziare il processo contro YSL.\n\n‼️Seguiranno aggiornamenti.\n.\n.\n.\n.\n#4theculture #youngthug #ysltrial #youngthugtrial #rap #trap #drill #hiphop #rapper #rapamericano', 'like_count': 543, 'permalink': 'https://www.instagram.com/p/Cy1Y24yNXxh/', 'timestamp': '2023-10-25T19:52:08+0000', 'comments_count': 6, 'media_type': 'IMAGE', 'id': '18389291317005097'}, {'caption': 'Keeping it real between takes and transitions 🎬\n\n#BBMAs #지민 #Jimin #정국 #Jungkook #Drake #WWERaw #JackSmith #CUTO #ysltrial #Chargers #fankraft\n#SelenaGomez #OnlyMurdersInTheBuilding #Canada #emiliaperezfilm #SelenaAndRestaurant #LoveOn #Netflix', 'like_count': 7, 'permalink': 'https://www.instagram.com/p/DC_Zr_qpYVL/', 'timestamp': '2024-11-30T10:34:02+0000', 'comments_count': 0, 'media_type': 'CAROUSEL_ALBUM', 'id': '18107471131447673'}, {'caption': 'Presiding #YSLTrial Judge Paige Reese Whitaker read the ‘n’ word out loud during proceedings today. Whitaker has since apologized citing she doesn’t use the word and meant no offensive.', 'like_count': 45, 'permalink': 'https://www.instagram.com/p/DCH3Ct0v1Gm/', 'timestamp': '2024-11-08T19:53:08+0000', 'comments_count': 20, 'media_type': 'CAROUSEL_ALBUM', 'id': '18022098068296999'}, {'caption': 'Severo ma giusto🤯\n\nIl papà di Young Thug ha commentato così, il video virale degli ultimi giorni, in cui Lil Baby, durante un live, ha dato del ‘ratto’ a Gunna.\n\n⏭️Scorri il post per saperne di più.\n\n👇🏻Che ne pensi della situazione?\n.\n.\n.\n.\n#4theculture #youngthug #lilbaby #gunna #rap #trap #drill #hiphop #rapper #rapamericano #ysltrial', 'like_count': 1277, 'permalink': 'https://www.instagram.com/p/C1HYnPqN8UT/', 'timestamp': '2023-12-21T12:39:07+0000', 'comments_count': 11, 'media_type': 'CAROUSEL_ALBUM', 'id': '18035159434638479'}, {'caption': '#YSLTrial might actually end in a mistrial and #YoungThug could possibly take a plea deal 👀', 'like_count': 778, 'permalink': 'https://www.instagram.com/p/DBhPOODTev2/', 'timestamp': '2024-10-24T19:54:02+0000', 'comments_count': 38, 'media_type': 'IMAGE', 'id': '17929842845842979'}, {'caption': '#YSLTrial continues on Monday at 9:00am for #YakGotti and #ShannonStillwell they both rejected all plea deals.', 'like_count': 390, 'permalink': 'https://www.instagram.com/p/DB0FlGeRX59/', 'timestamp': '2024-11-01T03:35:21+0000', 'comments_count': 27, 'media_type': 'IMAGE', 'id': '18056458387881418'}, {'caption': 'Judge in the #YSLtrial send prosecution witness to jail for 5 years 👀 y’all think he deserved it ⁉️🤔\n\n(Via: lawandcrime )', 'like_count': 1904, 'permalink': 'https://www.instagram.com/p/DBU76YlRID6/', 'timestamp': '2024-10-20T01:14:25+0000', 'comments_count': 69, 'media_type': 'CAROUSEL_ALBUM', 'id': '18043297886480362'}, {'caption': 'Si, hai sentito bene.🤯\n\nA distanza di appena 3 giorni dal suo inizio, il processo di Young Thug potrebbe essere dichiarato nullo.\n\nIl motivo? \nSembrerebbe che le identità di alcuni membri della giuria siano state compromesse, dopo esser apparse inavvertitamente durante una diretta streaming.\n\nIl giudice Glanville ha richiamato a se gli avvocati per un colloquio, e c’è tra le varie possibilità, potrebbe essere annunciato il ‘mistrial’.\n\nQuesto significherebbe che, così come sarà per Melly, verrà creata una nuova giuria e verrà iniziato un nuovo processo.\n\nPer il momento, nulla di certo.\nSeguiranno aggiornamenti.\n.\n.\n.\n.\n#4theculture #youngthugtrial #ysltrial #youngthug #rap #trap #drill #hiphop #rapper #rapamericano', 'like_count': 1039, 'permalink': 'https://www.instagram.com/p/C0RGdlaNp3V/', 'timestamp': '2023-11-30T10:41:31+0000', 'comments_count': 10, 'media_type': 'IMAGE', 'id': '17983567535544655'}, {'caption': '#JudgeGlanville has officially been removed from the #YSLTrial free #YoungThug 💯', 'like_count': 138, 'permalink': 'https://www.instagram.com/p/C9dE1ZuyolQ/', 'timestamp': '2024-07-15T19:00:44+0000', 'comments_count': 11, 'media_type': 'IMAGE', 'id': '17883130371083165'}, {'caption': 'Woah. Chief Judge Glanville will no longer over the YSL trial.\n\n#atatf #ysl #youngthug #ysltrial', 'like_count': 621, 'permalink': 'https://www.instagram.com/p/C9dHj9nP9tk/', 'timestamp': '2024-07-15T19:24:34+0000', 'comments_count': 25, 'media_type': 'CAROUSEL_ALBUM', 'id': '18320882110178059'}, {'caption': 'Le ultime sul caso YSL‼️\n\nUn altro membro del collettivo, questa volta Derontae Bebee, ha accettato il patteggiamento.\n\nUna scelta ambigua, visto che siamo a due settimane dall’inizio del processo, e soprattutto, visto che nel 2022, ne aveva già rifiutato uno, di patteggiamento.\n\nEra stato condannato a 15 anni, di cui: 5 in prigione e 10 di libertà vigilata.\n\nDei 28 iniziali membri di YSL arrestati, sono rimasti solo in 6, tra cui Young Thug, ad affrontare il processo, il cui inizio è segnato per il 27 novembre.\n\nSeguiranno aggiornamenti.\n\nChe ne pensi?\n.\n.\n.\n.\n#4theculture #youngthugtrial #youngthug #ysltrial #rap #trap #drill #hiphop #rapper #rapamericano', 'like_count': 562, 'permalink': 'https://www.instagram.com/p/CzbQYbxtFNy/', 'timestamp': '2023-11-09T12:49:13+0000', 'comments_count': 3, 'media_type': 'IMAGE', 'id': '18030872986631794'}, {'caption': 'The trial of Atlanta rapper Young Thug has ended in a guilty plea. Late in Thursday’s proceedings, the 33-year-old artist, whose real name is Jeffrery Williams, changed his plea in the RICO case to guilty and no contest on several gang, gun and drug charges.\u2060\n\u2060\nTap the link in our bio for more.', 'like_count': 2972, 'permalink': 'https://www.instagram.com/p/DB1jiKWsI7m/', 'timestamp': '2024-11-01T17:16:31+0000', 'comments_count': 109, 'media_type': 'IMAGE', 'id': '18471274093033360'}, {'caption': '#slimelifeshawty was back on the stand today in the #ysltrial pointing out individuals 👉🏼 rapspotsnews \nSwipe ➡️', 'like_count': 617, 'permalink': 'https://www.instagram.com/p/DB9_dZ0xf_t/', 'timestamp': '2024-11-04T23:54:17+0000', 'comments_count': 24, 'media_type': 'CAROUSEL_ALBUM', 'id': '18028950281151499'}], 'paging': {'cursors': {'after': 'NjBlOGQxMzEyZAGRhNGM4YjliOTk5MTNlZAmUwOWU2MTgZD'}, 'next': 'https://graph.facebook.com/v21.0/17844741295123663/top_media?access_token=EAANMSqWN3hsBO4GutpUYQzU7EQuECdKZAGL3ljzIZAkk4ZC29bpGp8n11K2kBzihbdfUohiTAoCVKrswGgMrfNce0kKcyhocySZBOkmwD1HDdeAdJ0jy1DhgkQB5g0n71gcd6RoiO2JZACVSDutYdctDLArJr5Nkhw4QBFiOm24yObQFGZAQh4bKvpPpYN2ZBDVxXZCV0GxzsSiYGRP5AAZDZD&user_id=17841407108401721&fields=caption%2Clike_count%2Cpermalink%2Ctimestamp%2Ccomments_count%2Cmedia_type&limit=25&after=NjBlOGQxMzEyZAGRhNGM4YjliOTk5MTNlZAmUwOWU2MTgZD'}}

In [53]:
b

{'data': [{'caption': '#youngthug’s lawyer now representing #problemchild ⚖️ rapspotsnews \nSwipe ➡️',
   'like_count': 1820,
   'permalink': 'https://www.instagram.com/p/DDxL4hlR6lR/',
   'timestamp': '2024-12-19T17:35:30+0000',
   'comments_count': 65,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18013719890662275'},
  {'caption': '#YoungThug has filed a new motion to be given bond with the new judge who was recently assigned to the #YslTrial case.',
   'permalink': 'https://www.instagram.com/p/C9yP2ThpgSt/',
   'timestamp': '2024-07-24T00:21:01+0000',
   'comments_count': 18,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18008405282548887'},
  {'caption': "In YSL's RICO Case The Judge Reads Lyrics Off Thug's Slime Sh- In Court\n\nUsing His Lyrics In Court Is Crazy I Can't Lie..What Happened To Freedom of Speech? Thoughts ??",
   'like_count': 621,
   'permalink': 'https://www.instagram.com/p/CnHbvp3jENH/',
   'timestamp': '2023-01-07T13:47:30+0000',
   'comments_count': 80,
   'media_type': 'VIDEO',
   'id': '18266528860114452'},
  {'caption': 'YSL Co-Founder Demonstrates Gang Signs in Court – A Shocking Tutorial Raises  Eyebrows. 🤔👀 #YSL #CourtroomControversy #YoungThug #YSLtrial',
   'like_count': 36,
   'permalink': 'https://www.instagram.com/p/C1pdT29PUHi/',
   'timestamp': '2024-01-03T18:14:20+0000',
   'comments_count': 3,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '17908442528808076'},
  {'caption': 'Looks like Mr. Thugger is already motivating the community & speaking to the upcoming lawyers at Emory Law School. Thoughts!? 🤔👇\n\n➕ Follow doaphouse for daily music updates, news & viral content!\n\n#youngthug #briansteel #thuggerthugger #emorylaw #ysltrial #freejeff #atlantarapper #atlrap #atlanatapolice #newmusicfriday #yslrecords #lawyer',
   'permalink': 'https://www.instagram.com/p/DCFWvBzzQkx/',
   'timestamp': '2024-11-07T20:32:21+0000',
   'comments_count': 8,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18052871134937422'},
  {'caption': 'We all know that #Wham is the nickname that #YoungThug uses for Lil Baby, so we think that whatever Lil Baby is doing on the outside YoungThug supports.... Hmm.. #Power983 #YSLTrial \n\n(Photo Credit: Arvin Temkar/Atlanta Journal-Constitution via AP, File)',
   'permalink': 'https://www.instagram.com/p/C8urrFWPDOU/',
   'timestamp': '2024-06-27T18:35:48+0000',
   'comments_count': 1,
   'media_type': 'IMAGE',
   'id': '18016393640380619'},
  {'caption': '🚨 BREAKING NEWS 🚨 Judge Ural Glanville presiding over the sweeping RICO indictment against Atlanta rapper Young Thug and his associates has been recused from the case. Judge Rachel Krause said in the motion that while the court has no doubt Glanville can and would continue presiding fairly over the case, but it is necessary to preserve “the public’s confidence in the judicial system.” The YSL Trial has been the subject of controversy since it started. 😳😬🏛️\n#YSLTrial #YoungThug #JudgeGlanville #BrianSteele #Atlanta #CultureClt™',
   'permalink': 'https://www.instagram.com/p/C9dIZoiB8iW/',
   'timestamp': '2024-07-15T19:31:54+0000',
   'comments_count': 0,
   'media_type': 'IMAGE',
   'id': '18023226593256628'},
  {'caption': 'Mannnn. What do yall think about this? 🤔\n#youngthug #gunna #ysltrial',
   'like_count': 1879,
   'permalink': 'https://www.instagram.com/p/C8uhezNCXBQ/',
   'timestamp': '2024-06-27T17:06:45+0000',
   'comments_count': 123,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18039000883787349'},
  {'caption': 'This the new judge on #YoungThug’s Rico court trial 👀 How we feeling bout this? \n\n-\n-\n-\n\n#youngthug #thug #thugger #youngthugger #ysl #yslcase #ysltrial #judge #courtroom #youngthugs #slime #slatt #explore #explorepage #exploremore #explorepage #explorepage✨',
   'permalink': 'https://www.instagram.com/p/C9i0Q6hJlK-/',
   'timestamp': '2024-07-18T00:31:23+0000',
   'comments_count': 4,
   'media_type': 'IMAGE',
   'id': '18038591872958710'},
  {'caption': '#ysltrial isn’t over yet and continues Monday with #yslsb and #yakgotti expecting to take it to the jury ⚖️ rapspotsnews',
   'like_count': 604,
   'permalink': 'https://www.instagram.com/p/DB4dWq7RSG1/',
   'timestamp': '2024-11-02T20:20:04+0000',
   'comments_count': 12,
   'media_type': 'IMAGE',
   'id': '18317631610095385'},
  {'caption': 'Ieri 27 novembre, è ufficialmente iniziato il processo contro YSL🤞🏻\n\nTrattandosi del primo giorno, non ci sono ancora state novità importanti…sono stati letti un paio di testi del rapper e gli sono state fatte le prime domande.\n\nSi stima che il processo duri dai 6 ai 9 mesi, di conseguenza, ne sentiremo parlare per un bel\npo’…\n\nSeguiranno aggiornamenti.\n.\n.\n.\n.\n#4theculture #youngthug #youngthugtrial #ysltrial #rap #trap #drill #hiphop #rapper #rapamericano',
   'like_count': 1107,
   'permalink': 'https://www.instagram.com/p/C0MAKZtNf8D/',
   'timestamp': '2023-11-28T11:10:16+0000',
   'comments_count': 7,
   'media_type': 'IMAGE',
   'id': '17989767533446039'},
  {'caption': 'Abbiamo una data📆\n\nSi prevede che il 27 novembre, possa finalmente iniziare il tanto atteso processo contro Young Thug, e in generale YSL.\n\nDopo mesi di lavoro, qualche ora fa, è finalmente terminata la selezione della giuria, che sarà formata da 12 persone, più 6 eventuali sostituti.\n\nIl processo dovrebbe durare dai 6 ai 9 mesi, il che lo renderebbe, il più lungo nella storia della Georgia.\n\nNon ci resta che aspettare e sperare che vada tutto bene.\n\nSeguiranno aggiornamenti.\n.\n.\n.\n.\n#4theculture #youngthug #ysl #youngthugtrial #ysltrial #rap #trap #drill #hiphop #rapper #rapamericano',
   'like_count': 922,
   'permalink': 'https://www.instagram.com/p/CzJJVVDtFsA/',
   'timestamp': '2023-11-02T12:01:17+0000',
   'comments_count': 11,
   'media_type': 'IMAGE',
   'id': '18018357283884638'},
  {'caption': 'Ci sono piccoli progressi per quanto riguarda il processo di Young Thug👀\n\n📲Sono stati ufficialmente selezionati 50 ‘probabili’ giurati, sui circa 1000 iniziali.\nQuesto significa che ora, passeremo allo step successivo.\n\nL’accusa e la difesa interrogheranno i restanti 50 giurati, decidendo chi scartare, per passare alla prossima fase.\n\nCiò andrà avanti fin quando rimarranno 12 giurati, più gli eventuali sostituti.\n\nPoiché si prevede un lungo processo, che durerà dai 6 ai 9 mesi, il giudice, molto probabilmente, richiederà un gran numero di sostituti, che entreranno in gioco solo nel caso in cui, qualcuno dei 12 prescelti dovesse abbandonare il processo, per qualsiasi tipo di emergenza.\n\nQuesto significa che questa fase, teoricamente, dovrebbe durare molto di meno rispetto alle precedenti e, una volta terminata, potrà finalmente iniziare il processo contro YSL.\n\n‼️Seguiranno aggiornamenti.\n.\n.\n.\n.\n#4theculture #youngthug #ysltrial #youngthugtrial #rap #trap #drill #hiphop #rapper #rapamericano',
   'like_count': 543,
   'permalink': 'https://www.instagram.com/p/Cy1Y24yNXxh/',
   'timestamp': '2023-10-25T19:52:08+0000',
   'comments_count': 6,
   'media_type': 'IMAGE',
   'id': '18389291317005097'},
  {'caption': 'Keeping it real between takes and transitions 🎬\n\n#BBMAs #지민 #Jimin #정국 #Jungkook #Drake #WWERaw #JackSmith #CUTO #ysltrial #Chargers #fankraft\n#SelenaGomez #OnlyMurdersInTheBuilding #Canada #emiliaperezfilm #SelenaAndRestaurant #LoveOn #Netflix',
   'like_count': 7,
   'permalink': 'https://www.instagram.com/p/DC_Zr_qpYVL/',
   'timestamp': '2024-11-30T10:34:02+0000',
   'comments_count': 0,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18107471131447673'},
  {'caption': 'Presiding #YSLTrial Judge Paige Reese Whitaker read the ‘n’ word out loud during proceedings today. Whitaker has since apologized citing she doesn’t use the word and meant no offensive.',
   'like_count': 45,
   'permalink': 'https://www.instagram.com/p/DCH3Ct0v1Gm/',
   'timestamp': '2024-11-08T19:53:08+0000',
   'comments_count': 20,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18022098068296999'},
  {'caption': 'Severo ma giusto🤯\n\nIl papà di Young Thug ha commentato così, il video virale degli ultimi giorni, in cui Lil Baby, durante un live, ha dato del ‘ratto’ a Gunna.\n\n⏭️Scorri il post per saperne di più.\n\n👇🏻Che ne pensi della situazione?\n.\n.\n.\n.\n#4theculture #youngthug #lilbaby #gunna #rap #trap #drill #hiphop #rapper #rapamericano #ysltrial',
   'like_count': 1277,
   'permalink': 'https://www.instagram.com/p/C1HYnPqN8UT/',
   'timestamp': '2023-12-21T12:39:07+0000',
   'comments_count': 11,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18035159434638479'},
  {'caption': '#YSLTrial might actually end in a mistrial and #YoungThug could possibly take a plea deal 👀',
   'like_count': 778,
   'permalink': 'https://www.instagram.com/p/DBhPOODTev2/',
   'timestamp': '2024-10-24T19:54:02+0000',
   'comments_count': 38,
   'media_type': 'IMAGE',
   'id': '17929842845842979'},
  {'caption': '#YSLTrial continues on Monday at 9:00am for #YakGotti and #ShannonStillwell they both rejected all plea deals.',
   'like_count': 390,
   'permalink': 'https://www.instagram.com/p/DB0FlGeRX59/',
   'timestamp': '2024-11-01T03:35:21+0000',
   'comments_count': 27,
   'media_type': 'IMAGE',
   'id': '18056458387881418'},
  {'caption': 'Judge in the #YSLtrial send prosecution witness to jail for 5 years 👀 y’all think he deserved it ⁉️🤔\n\n(Via: lawandcrime )',
   'like_count': 1904,
   'permalink': 'https://www.instagram.com/p/DBU76YlRID6/',
   'timestamp': '2024-10-20T01:14:25+0000',
   'comments_count': 69,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18043297886480362'},
  {'caption': 'Si, hai sentito bene.🤯\n\nA distanza di appena 3 giorni dal suo inizio, il processo di Young Thug potrebbe essere dichiarato nullo.\n\nIl motivo? \nSembrerebbe che le identità di alcuni membri della giuria siano state compromesse, dopo esser apparse inavvertitamente durante una diretta streaming.\n\nIl giudice Glanville ha richiamato a se gli avvocati per un colloquio, e c’è tra le varie possibilità, potrebbe essere annunciato il ‘mistrial’.\n\nQuesto significherebbe che, così come sarà per Melly, verrà creata una nuova giuria e verrà iniziato un nuovo processo.\n\nPer il momento, nulla di certo.\nSeguiranno aggiornamenti.\n.\n.\n.\n.\n#4theculture #youngthugtrial #ysltrial #youngthug #rap #trap #drill #hiphop #rapper #rapamericano',
   'like_count': 1039,
   'permalink': 'https://www.instagram.com/p/C0RGdlaNp3V/',
   'timestamp': '2023-11-30T10:41:31+0000',
   'comments_count': 10,
   'media_type': 'IMAGE',
   'id': '17983567535544655'},
  {'caption': '#JudgeGlanville has officially been removed from the #YSLTrial free #YoungThug 💯',
   'like_count': 138,
   'permalink': 'https://www.instagram.com/p/C9dE1ZuyolQ/',
   'timestamp': '2024-07-15T19:00:44+0000',
   'comments_count': 11,
   'media_type': 'IMAGE',
   'id': '17883130371083165'},
  {'caption': 'Woah. Chief Judge Glanville will no longer over the YSL trial.\n\n#atatf #ysl #youngthug #ysltrial',
   'like_count': 621,
   'permalink': 'https://www.instagram.com/p/C9dHj9nP9tk/',
   'timestamp': '2024-07-15T19:24:34+0000',
   'comments_count': 25,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18320882110178059'},
  {'caption': 'Le ultime sul caso YSL‼️\n\nUn altro membro del collettivo, questa volta Derontae Bebee, ha accettato il patteggiamento.\n\nUna scelta ambigua, visto che siamo a due settimane dall’inizio del processo, e soprattutto, visto che nel 2022, ne aveva già rifiutato uno, di patteggiamento.\n\nEra stato condannato a 15 anni, di cui: 5 in prigione e 10 di libertà vigilata.\n\nDei 28 iniziali membri di YSL arrestati, sono rimasti solo in 6, tra cui Young Thug, ad affrontare il processo, il cui inizio è segnato per il 27 novembre.\n\nSeguiranno aggiornamenti.\n\nChe ne pensi?\n.\n.\n.\n.\n#4theculture #youngthugtrial #youngthug #ysltrial #rap #trap #drill #hiphop #rapper #rapamericano',
   'like_count': 562,
   'permalink': 'https://www.instagram.com/p/CzbQYbxtFNy/',
   'timestamp': '2023-11-09T12:49:13+0000',
   'comments_count': 3,
   'media_type': 'IMAGE',
   'id': '18030872986631794'},
  {'caption': 'The trial of Atlanta rapper Young Thug has ended in a guilty plea. Late in Thursday’s proceedings, the 33-year-old artist, whose real name is Jeffrery Williams, changed his plea in the RICO case to guilty and no contest on several gang, gun and drug charges.\u2060\n\u2060\nTap the link in our bio for more.',
   'like_count': 2972,
   'permalink': 'https://www.instagram.com/p/DB1jiKWsI7m/',
   'timestamp': '2024-11-01T17:16:31+0000',
   'comments_count': 109,
   'media_type': 'IMAGE',
   'id': '18471274093033360'},
  {'caption': '#slimelifeshawty was back on the stand today in the #ysltrial pointing out individuals 👉🏼 rapspotsnews \nSwipe ➡️',
   'like_count': 617,
   'permalink': 'https://www.instagram.com/p/DB9_dZ0xf_t/',
   'timestamp': '2024-11-04T23:54:17+0000',
   'comments_count': 24,
   'media_type': 'CAROUSEL_ALBUM',
   'id': '18028950281151499'}],
 'paging': {'cursors': {'after': 'NjBlOGQxMzEyZAGRhNGM4YjliOTk5MTNlZAmUwOWU2MTgZD'},
  'next': 'https://graph.facebook.com/v21.0/17844741295123663/top_media?access_token=EAANMSqWN3hsBO4GutpUYQzU7EQuECdKZAGL3ljzIZAkk4ZC29bpGp8n11K2kBzihbdfUohiTAoCVKrswGgMrfNce0kKcyhocySZBOkmwD1HDdeAdJ0jy1DhgkQB5g0n71gcd6RoiO2JZACVSDutYdctDLArJr5Nkhw4QBFiOm24yObQFGZAQh4bKvpPpYN2ZBDVxXZCV0GxzsSiYGRP5AAZDZD&user_id=17841407108401721&fields=caption%2Clike_count%2Cpermalink%2Ctimestamp%2Ccomments_count%2Cmedia_type&limit=25&after=NjBlOGQxMzEyZAGRhNGM4YjliOTk5MTNlZAmUwOWU2MTgZD'}}

In [48]:
import pandas as pd

ysl_trial_top_media = pd.DataFrame(b['data'])

In [49]:
ysl_trial_top_media

,caption,like_count,permalink,timestamp,comments_count,id
0,#youngthug’s lawyer now representing #problemc...,1820.0,https://www.instagram.com/p/DDxL4hlR6lR/,2024-12-19T17:35:30+0000,65,18013719890662275
1,#YoungThug has filed a new motion to be given ...,NaN,https://www.instagram.com/p/C9yP2ThpgSt/,2024-07-24T00:21:01+0000,18,18008405282548887
2,In YSL's RICO Case The Judge Reads Lyrics Off ...,621.0,https://www.instagram.com/p/CnHbvp3jENH/,2023-01-07T13:47:30+0000,80,18266528860114452
3,YSL Co-Founder Demonstrates Gang Signs in Cour...,36.0,https://www.instagram.com/p/C1pdT29PUHi/,2024-01-03T18:14:20+0000,3,17908442528808076
4,Looks like Mr. Thugger is already motivating t...,NaN,https://www.instagram.com/p/DCFWvBzzQkx/,2024-11-07T20:32:21+0000,8,18052871134937422
5,We all know that #Wham is the nickname that #Y...,NaN,https://www.instagram.com/p/C8urrFWPDOU/,2024-06-27T18:35:48+0000,1,18016393640380619
6,🚨 BREAKING NEWS 🚨 Judge Ural Glanville presidi...,NaN,https://www.instagram.com/p/C9dIZoiB8iW/,2024-07-15T19:31:54+0000,0,18023226593256628
7,Mannnn. What do yall think about this? 🤔\n#you...,1879.0,https://www.instagram.com/p/C8uhezNCXBQ/,2024-06-27T17:06:45+0000,123,18039000883787349
8,#ysltrial isn’t over yet and continues Monday ...,604.0,https://www.instagram.com/p/DB4dWq7RSG1/,2024-11-02T20:20:04+0000,12,18317631610095385
9,This the new judge on #YoungThug’s Rico court ...,NaN,https://www.instagram.com/p/C9i0Q6hJlK-/,2024-07-18T00:31:23+0000,4,18038591872958710
10,"Ieri 27 novembre, è ufficialmente iniziato il ...",1107.0,https://www.instagram.com/p/C0MAKZtNf8D/,2023-11-28T11:10:16+0000,7,17989767533446039
11,Abbiamo una data📆\n\nSi prevede che il 27 nove...,922.0,https://www.instagram.com/p/CzJJVVDtFsA/,2023-11-02T12:01:17+0000,11,18018357283884638
12,Ci sono piccoli progressi per quanto riguarda ...,543.0,https://www.instagram.com/p/Cy1Y24yNXxh/,2023-10-25T19:52:08+0000,6,18389291317005097
13,Keeping it real between takes and transitions ...,7.0,https://www.instagram.com/p/DC_Zr_qpYVL/,2024-11-30T10:34:02+0000,0,18107471131447673
14,Presiding #YSLTrial Judge Paige Reese Whitaker...,45.0,https://www.instagram.com/p/DCH3Ct0v1Gm/,2024-11-08T19:53:08+0000,20,18022098068296999
15,Severo ma giusto🤯\n\nIl papà di Young Thug ha ...,1277.0,https://www.instagram.com/p/C1HYnPqN8UT/,2023-12-21T12:39:07+0000,11,18035159434638479
16,#YSLTrial might actually end in a mistrial and...,778.0,https://www.instagram.com/p/DBhPOODTev2/,2024-10-24T19:54:02+0000,38,17929842845842979
17,#YSLTrial continues on Monday at 9:00am for #Y...,390.0,https://www.instagram.com/p/DB0FlGeRX59/,2024-11-01T03:35:21+0000,27,18056458387881418
18,Judge in the #YSLtrial send prosecution witnes...,1904.0,https://www.instagram.com/p/DBU76YlRID6/,2024-10-20T01:14:25+0000,69,18043297886480362
19,"Si, hai sentito bene.🤯\n\nA distanza di appena...",1039.0,https://www.instagram.com/p/C0RGdlaNp3V/,2023-11-30T10:41:31+0000,10,17983567535544655
20,#JudgeGlanville has officially been removed fr...,138.0,https://www.instagram.com/p/C9dE1ZuyolQ/,2024-07-15T19:00:44+0000,11,17883130371083165
21,Woah. Chief Judge Glanville will no longer ove...,621.0,https://www.instagram.com/p/C9dHj9nP9tk/,2024-07-15T19:24:34+0000,25,18320882110178059
22,Le ultime sul caso YSL‼️\n\nUn altro membro de...,562.0,https://www.instagram.com/p/CzbQYbxtFNy/,2023-11-09T12:49:13+0000,3,18030872986631794
23,The trial of Atlanta rapper Young Thug has end...,2972.0,https://www.instagram.com/p/DB1jiKWsI7m/,2024-11-01T17:16:31+0000,109,18471274093033360
24,#slimelifeshawty was back on the stand today i...,617.0,https://www.instagram.com/p/DB9_dZ0xf_t/,2024-11-04T23:54:17+0000,24,18028950281151499

In [54]:
ysl_trial_top_media.to_csv('ysl_trial_top_instagram.csv')

In [55]:
graph_url = 'https://graph.facebook.com/v15.0/'
def get_recent_media(hashtag_id='',access_token = '',instagram_account_id = ''):
    url = graph_url + hashtag_id + '/recent_media'
    param = dict()
    param['access_token'] = access_token
    param['user_id'] = instagram_account_id
    param['fields'] = 'caption,like_count,permalink'
    response = requests.get(url, param)
    response = response.json()
    print(response)
    return response

In [36]:
c = get_recent_media(instagram_hashtag_id,
                     access_token=access_token,
                     instagram_account_id=instagram_id)

{'data': [{'caption': 'NOT GUILTY‼️Make it make sense‼️#jacepartyfavorsanddesigns01 #custommade #explorepage #reelsinstagram #jacepartyfavors #customshirts #yakgotti #ysltrial #youngthug #notguilty', 'like_count': 4, 'permalink': 'https://www.instagram.com/reel/DD5rFyNu6mK/', 'id': '18053057561006107'}, {'caption': 'I don’t own the rights to this music. Deamonte Kendrick professionally known as Yak Gotti was found not guilty by a jury of his peers. Several attempts were made to take his life so he had to defend himself. During a hearing, there was a warrant that mysteriously appeared out of the air regarding his probation. The warrant was a result of being charged in this conspiracy to commit RICO. The judge ruled if there was no warrant, he would be released. A warrant was filled the next day signed by a judge that had nothing to do with his hearing.💸💸💸This is an injustice to everyone. Please don’t put on blinders. There was no evidence related to Yak in this case. Fulton County strikes again. Please share & if you are in Atlanta please try to attend. Pay attention. My heart aches for his mother.\n\nTomorrow, December 23rd\n10am -1pm\nAtlanta, GA\n\n‼️Stand Against the Injustices happening toward Deamonte Kendrick (Yak Gotti). He was found Not Guilty by a jury, yet still being held in Fulton Co jail.‼️\n\nMake your voice heard… #FreeYakGotti\n\n#YakGotti #YSLTrial', 'like_count': 3, 'permalink': 'https://www.instagram.com/reel/DD5eJhYvod3/', 'id': '18064417474662776'}]}

In [37]:
ysl_trial_recent_media = pd.DataFrame(c['data'])

In [38]:
ysl_trial_recent_media

,caption,like_count,permalink,id
0,NOT GUILTY‼️Make it make sense‼️#jacepartyfavo...,4,https://www.instagram.com/reel/DD5rFyNu6mK/,18053057561006107
1,I don’t own the rights to this music. Deamonte...,3,https://www.instagram.com/reel/DD5eJhYvod3/,18064417474662776

In [39]:
ysl_trial_recent_media.to_csv('ysl_trial_recent_instagram.csv')